### PR TITLE
Demo Fix: Catch Socket Frames Before They Inflict Maximum Damage

### PR DESCRIPTION
**Pull request by sumanyuj**
This is a light PR to enhance sockets by modifying the receive function to check for frame sizes, and rejected (or ejecting) if it catches what we deem a too large frame. 

Please test and approve asap, due to demo.

### CODE REVIEW

**Review by giagermain — DISMISSED** [review]
lgtm

**Comment by sumanyuj** [comment]
Added csrf to logout view to fix logout.

**Review by giagermain — APPROVED** [review]
lgtm

**Comment by WeirdAlex03** [comment]
This has been deployed on the server

**Pull request merged**
